language: python
sudo: false

python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'

install:
  pip install -U pytest .

script:
  py.test

notification:
  email:
    on_success: change
    on_failure: change
